# Dependencies
markdown:         kramdown
highlighter:      rouge  

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            Dhron
tagline:          'Life of a CS Undergrad'
description:      'University of Waterloo ''20 | CS' 
url:               http://www.dhron.co
baseurl:          http://www.dhron.co

author:
  name:           'Dhron Joshi'
  url:            https://twitter.com/dhron

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/Dhron/dhron.github.io
plugins: [jekyll-paginate]
quora: https://www.quora.com/dhron-joshi
insta: https://www.instagram.com/dhronj
twitter: https://www.twitter.com/dhronj
email: mailto:dhron.joshi@hotmail.com
resume: /resume.pdf
